"""The participant documents, generated from the code (T1-RES-04, 05, 14, 15, 16).

7-A4 splits the statement from the starter kit: `../track1.html` carries the task, the
semantics and the behavioural warnings; **every number** -- dtypes, shapes, ranges,
palette values, beam counts, limits -- lives in the kit's schema document and its example
dumps. A document that restates numbers by hand drifts from the code that produces them,
so this module *is* the document: `usvnav docs` writes `docs/` from the same constants
and the same observation loop the scorer runs, and `tests/internal/test_docs.py` fails
the suite if the committed files differ from what the code generates.

What is written:

    docs/OBSERVATION.md     the observation and action schema (T1-RES-04)
    docs/examples/          one course, its reset metadata, and one observation per
                            condition, captured from `sim.run_episode` (T1-RES-05)
    docs/RULES.md           submission and execution rules, scoring, what is published,
                            what is still provisional (T1-RES-14)
    docs/RUNTIME.md         what a submission meets at scoring time (T1-RES-15)
    docs/PACKAGING.md       the submission directory, its manifest, and every check the
                            local validator applies (T1-RES-16, T1-RES-17)

The prose is here rather than in Markdown files because the prose *names the numbers*:
"180 beams" is a sentence in which 180 is `lidar.N_BEAMS`, and a sentence that carries a
value has to be built where the value is. Semantics that are not numbers -- why no-return
is the maximum range rather than zero -- are repeated from the statement deliberately,
because an agent built on the wrong reading is structurally wrong (7-A4).
"""

from __future__ import annotations

import json
import pathlib

import numpy as np

from . import __version__, coursefile, plant, runtime
from . import look as _look
from .contest import CLEARANCE_PERCENTILE, CONDITION_WEIGHTS, D_CAP, WEIGHTS
from .lanerules import LANE_TURN_MAX_DEG
from .lidar import MAX_RANGE, N_BEAMS
from .objects import CAPACITY, CIRCLE, CLASSES, RECT
from .rules import LEG_MAX, LEG_MIN, RADIUS_GOAL, RADIUS_INTERMEDIATE, WP_MAX, WP_MIN
from .png import write_png
from .render import COLOUR_OF, PALETTE_TRACK1, TRACK1
from .sim import (BUDGET_CAPS, NAVIGATIONAL, PERSISTENT_TICKS, SENSING_RANGE, SUBMISSION_FAULT,
                  TICK_CAP_MS, TICK_CAP_MULTIPLE, TICK_FLOOR_MS, TICK_LIMIT, run_episode)
from .submission import CHECKS, DOC, FORMAT, MANIFEST, REQUIRED, SIZE_CAP_BYTES, TEAM_RE
from .world import (A_MAX, BANK, BUOY, DOCK, EGO, EGO_SLOT, LANE_CLEAR, MOORED, MOVING, OUTSIDE_WORLD, PIER, SIZE_RANGES, TRAFFIC_SPEED_MAX, TRAFFIC_SPEED_MIN, UNOBSERVED, V_WAIT, WATER)

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

#: The example dumps come from the course committed beside them, `docs/examples/course.json`
#: -- a scored course is the file (follow-up item 6), and the generator that once drew it
#: does not ship (7-A8), so the document generator reads the file rather than generating.
#: The organisers regenerate the file with `python -m usvnav.internal generate` when the
#: world changes; it has moving vessels in it so the 1-1 list shows a non-zero velocity.
#: The tutorial agent drives to this tick under each condition; `DUMP_SEED` is the 1-4
#: disturbance seed.
DUMP_SEED = 4250
DUMP_TICK = 120

CONDITIONS = ("1-1", "1-2", "1-3", "1-4")
STAMP = f"*Generated by `usvnav docs` from usvnav {__version__}. Do not edit; edit the code.*"


# --------------------------------------------------------------------------- capture

def _course():
    path = DOCS / "examples" / "course.json"
    if not path.is_file():                               # pragma: no cover
        raise RuntimeError(f"{path} is missing; the organisers regenerate it with "
                           f"`python -m usvnav.internal generate --scenario traffic --seed 4250`")
    return coursefile.load(path)


def capture(course, condition: str, tick: int = DUMP_TICK):
    """`(meta, obs)` at `tick`, from the scoring loop itself (7-A2)."""
    from .agent import TutorialAgent

    got = {}

    def hook(t, meta, obs):
        if t == tick:
            got["meta"], got["obs"] = meta, obs

    res = run_episode(course, TutorialAgent(), condition=condition, seed=DUMP_SEED,
                      tick_limit=tick + 1, on_observation=hook)
    if "obs" not in got:                                 # pragma: no cover
        raise RuntimeError(f"the episode ended as {res.outcome} at {res.ticks} < {tick}")
    return got["meta"], got["obs"]


def _listify(v):
    if isinstance(v, dict):
        return {k: _listify(x) for k, x in v.items()}
    if isinstance(v, np.ndarray):
        return np.round(v, 4).tolist() if v.dtype.kind == "f" else v.tolist()
    if isinstance(v, (np.generic,)):
        return v.item()
    if isinstance(v, (list, tuple)):
        return [_listify(x) for x in v]
    return v


def _shape(v):
    a = np.asarray(v)
    return f"`{a.dtype}`", ("scalar" if a.shape == () else "×".join(str(n) for n in a.shape))


# --------------------------------------------------------------------------- helpers

def _table(head, rows):
    out = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return out


def _hex(rgb):
    return "#%02X%02X%02X" % tuple(rgb)


def _fmt(v, nd=3):
    a = np.asarray(v)
    if a.shape == ():
        return f"{a.item():.{nd}f}" if a.dtype.kind == "f" else str(a.item())
    return "[" + ", ".join(f"{x:.{nd}f}" if a.dtype.kind == "f" else str(x)
                           for x in a.reshape(-1)[:6]) + (", …" if a.size > 6 else "") + "]"


# --------------------------------------------------------------------------- OBSERVATION.md

def observation_md(course, captures: dict) -> str:
    meta, obs11 = captures["1-1"]
    obs12, obs13, obs14 = captures["1-2"][1], captures["1-3"][1], captures["1-4"][1]
    ol, img, scan = obs11["perception"], obs12["perception"], obs13["perception"]
    L = []
    a = L.append

    a("# Track 1 — observation and action schema")
    a("")
    a(STAMP)
    a("")
    a("This is where the numbers live. The problem statement carries the task, the meaning "
      "of each field and the warnings that change how an agent is designed; this document "
      "carries every dtype, shape, range, sentinel and constant, and `docs/examples/` "
      "carries one real observation per condition captured from the scoring loop. If a "
      "number here disagrees with the statement, this document is right and the statement "
      "is stale (7-A4).")
    a("")
    a("The interface, in full (6-R6, 6-R8):")
    a("")
    a("```python")
    a("class Agent:")
    a("    def __init__(self, config_path): ...      # once per process; a path inside your submission")
    a("    def reset(self, meta): ...                # once per episode; clear all state here")
    a("    def act(self, obs) -> [v_cmd, w_cmd]: ... # every tick, 10 Hz simulated time")
    a("```")
    a("")
    a("No state may carry from one episode to the next; `reset` is where it is cleared. "
      "There is no end-of-episode callback: scoring learns nothing, so there is nothing to "
      "tell you.")
    a("")

    # ---- conventions
    a("## 1. Units, frames and signs (1-W3)")
    a("")
    a("SI units throughout: metres, seconds, radians. Every angle in every array is in "
      "radians and wrapped to (−π, π].")
    a("")
    a("**World frame:** right-handed 2D, `+x` along the reach's long axis, `+y` 90° "
      "counter-clockwise from it; heading ψ is measured counter-clockwise from `+x` to "
      "the bow.")
    a("")
    a("**Body frame:** origin at the hull rectangle's centre, `+x` through the bow, `+y` to "
      "**port**. A positive `w_cmd`, a positive yaw rate, a positive bearing and a LiDAR "
      "beam index increasing from the bow all mean the same direction: **to port, "
      "counter-clockwise seen from above**. Under this convention \"obstacle at beam 30 → "
      "bearing +60° → steer positive\" turns *toward* it, which is the trap the convention "
      "exists to make visible.")
    a("")
    a(f"**Raster mapping** (`bow_up`, 4-V2): a body-frame point `(x_b, y_b)` lands at "
      f"`row = {TRACK1.origin_px:.1f} − x_b / {TRACK1.m_per_px}`, "
      f"`col = {TRACK1.origin_px:.1f} − y_b / {TRACK1.m_per_px}` in continuous pixel "
      f"coordinates, so the hull centre sits on the corner shared by the four central "
      f"pixels, the bow points to row 0, and port is to the *left* of the image (a point "
      f"10 m ahead and 10 m to port lands upper-left).")
    a("")

    # ---- reset metadata
    a("## 2. Episode start — `reset(meta)` (4-V1)")
    a("")
    a("`meta` is a dict. It is identical in all four conditions and carries **no obstacle "
      "geometry**: perceiving the surroundings is the task.")
    a("")
    wps = np.asarray(meta["waypoints"])
    radii = np.asarray(meta["arrival_radii"])
    L += _table(("key", "type", "example", "meaning"), [
        ("`boundary`", f"`float64` N×2 (here N = {len(meta['boundary'])})",
         f"`{_fmt(np.asarray(meta['boundary'])[0], 2)}` …",
         "the navigable polygon in world metres — the shoreline (2-E6). Water inside, bank "
         "outside; any part of the hull crossing it ends the episode as `out_of_bounds`"),
        ("`waypoints`", f"`float64` K×2 (here K = {len(wps)})", f"`{_fmt(wps[0], 2)}` …",
         "the full ordered chain in world metres, to be reached **in order** (3-K11)"),
        ("`arrival_radii`", f"`float64` K", f"`{_fmt(radii, 1)}`",
         f"metres; reaching waypoint k means the hull **centre** comes within radius k. "
         f"Intermediate waypoints {radii[0]:.0f} m, the goal {radii[-1]:.0f} m"),
        ("`hull`", "`(float, float)`", f"`{tuple(meta['hull'])}`",
         f"length and width in metres. **A constant** — {plant.HULL_LENGTH} × "
         f"{plant.HULL_WIDTH} m in every episode and every condition (1-W4); it is here "
         f"because 4-V1 enumerates what is disclosed, not because it varies"),
        ("`observation_mode`", "`str`", f"`{meta['observation_mode']!r}`",
         "one of `1-1`, `1-2`, `1-3`, `1-4`; fixed for the episode and decides the type "
         "of `obs[\"perception\"]`"),
    ])
    a("")
    a(f"The start is stationary, at the departure berth, heading aligned with the first leg "
      f"plus a per-episode offset of up to ±30° (3-K11). Courses have {WP_MIN}–{WP_MAX} waypoints on legs "
      f"of {LEG_MIN:g}–{LEG_MAX:g} m (3-K5); a course may run down the reach and back, with its goal "
      f"beside its start.")
    a("")

    # ---- action
    a("## 3. The action — `act(obs) -> [v_cmd, w_cmd]` (1-W5, 1-W6)")
    a("")
    a("Two numbers, in any array-like of length 2: a **surge setpoint** in m/s and a "
      "**yaw-rate setpoint** in rad/s. They are setpoints, not forces: an autopilot turns them "
      "into thrust for the vessel, which is **Track 2's public nominal model** (`usvnav/plant.py`: "
      "a planar rigid body with linear damping, a stern azimuth thruster and a bow thruster). "
      "The hull has inertia and slips: a turn pushes the stern sideways, a hard turn at speed "
      "bleeds speed because the stern thruster's thrust is shared between surge and turning, "
      "the yaw rate you can have falls as speed rises, and a lower speed setpoint throttles back "
      "and coasts rather than braking — only a negative `v_cmd` reverses.")
    a("")
    L += _table(("quantity", "value", "decision"), [
        ("`v_cmd` range", f"[{plant.V_MIN}, {plant.V_MAX}] m/s; cruise {plant.V_CRUISE} m/s", "1-W5"),
        ("`w_cmd` range", f"[−{plant.W_MAX}, {plant.W_MAX}] rad/s", "1-W5"),
        ("slew limits, applied by the simulator", f"{plant.SLEW_V} m/s and {plant.SLEW_W} rad/s per tick", "1-W5"),
        ("vessel", f"{plant.MASS:.0f} kg, damping X_u {plant.X_U:.0f} / Y_v {plant.Y_V:.0f} N·s/m, "
                   f"N_r {plant.N_R:.0f} N·m·s; stern {plant.K_STERN:.0f} N (reverse {100 * plant.REVERSE_MAX:.0f} %), "
                   f"bow {plant.K_BOW:.0f} N, arm {plant.ARM} m", "1-W5 (§9.33)"),
        ("what a hard turn at full speed does", "about 1.6 m/s and 0.5 rad/s, the hull slipping ~10°", "1-W5 (§9.33)"),
        ("control period", f"{plant.DT} s (10 Hz), simulated — the runner waits for `act`", "1-W5, 6-R7"),
        ("out-of-range but finite", "clipped to the range; the episode continues; "
                                    "`prev_action` shows the clipped value next tick", "1-W6"),
        ("NaN, ±inf, wrong shape, exception", "ends the episode as `invalid_action` / `crash`, "
                                              "a submission fault scoring 0", "1-W6, 5-S11"),
    ])
    a("")
    a("The 1-4 disturbance enters as a **lateral drift with no yaw moment**, so turn "
      "authority is untouched by it; holding a straight course at cruise against the "
      "maximum drift needs about a 13° crab angle (4-V10).")
    a("")

    # ---- common fields
    a("## 4. Common observation fields (4-V15)")
    a("")
    a("`obs` is a dict of named numpy arrays — never a flat vector. These six keys are "
      "present, with these types, in every condition. Real values are `float32`; the "
      "simulator integrates in `float64` and rounds on emission.")
    a("")
    meanings = {
        "t": "control tick since `reset`, 0-based; the time limit (§6) is in the same unit",
        "pose": "`x, y` in world metres and heading ψ in radians, wrapped — your GNSS and compass",
        "vel": "surge `u`, sway `v` (m/s, **over ground, body axes**) and yaw rate `r` (rad/s). "
               "`v` is the hull's slip: nonzero whenever it turns, in every condition, and under 1-4 "
               "it also carries the disturbance",
        "wp_index": "index into `meta[\"waypoints\"]` of the waypoint you are heading for now",
        "wp_polar": "distance in metres and **bow-relative bearing** in radians to that waypoint, "
                    "wrapped; positive is to port. Redundant with `pose` and supplied so nobody "
                    "re-implements the wrap",
        "prev_action": "the command **actually applied** last tick — after clipping — which can "
                       "differ from what you returned. `[0, 0]` at `t = 0`",
    }
    rows = []
    for k in ("t", "pose", "vel", "wp_index", "wp_polar", "prev_action"):
        dt, sh = _shape(obs14[k])
        rows.append((f"`{k}`", dt, sh, f"`{_fmt(obs14[k])}`", meanings[k]))
    L += _table(("field", "dtype", "shape", "example (1-4, tick %d)" % DUMP_TICK, "meaning"), rows)
    a("")
    a("Deliberately absent: obstacle information of any kind (that is `perception`), the "
      "disturbance state, remaining time (compute it from `t`), and any success or failure "
      "flag.")
    a("")

    # ---- perception
    a("## 5. `obs[\"perception\"]`, per condition")
    a("")
    a(f"Sensing range is {SENSING_RANGE:.0f} m (4-V5). For 1-3 that is a radius; for 1-1, "
      f"1-2 and 1-4 it is the half-width of a {2 * SENSING_RANGE:.0f} × {2 * SENSING_RANGE:.0f} m "
      f"square centred on the hull, which reaches {TRACK1.reach_m:.2f} m into its corners "
      f"(4-V6, 4-V18). Every observation is exact: no sensor noise, and the scoring renderer "
      f"adds no noise (4-V14, revised 2026-09-16 — renderer noise exists only as an option "
      f"you switch on yourself in the studio or with `--noise`, see 5.2).")
    a("")

    # 1-1
    a("### 5.1 Condition 1-1 — structured object list (4-V4, 4-V18)")
    a("")
    a(f"A dict of fixed-length arrays with a validity mask, capacity {CAPACITY}, rows "
      f"**nearest first**, zero-padded. A body is listed when its footprint intersects the "
      f"observation square. Occluded bodies are listed — there is no visibility test.")
    a("")
    rows = []
    desc = {
        "valid": "row `i` is a body; rows after the last valid one are zero padding",
        "cls": "object class id, table below",
        "primitive": f"{CIRCLE} = circle, {RECT} = oriented rectangle (2-E3)",
        "pos": "body centre in the **body frame**, metres: `+x` ahead, `+y` to port",
        "heading": "the body's heading relative to yours, radians, wrapped (0 for a circle)",
        "vel": "the body's **over-ground** velocity, components in **your** axes, m/s. Static "
               "bodies are exactly `[0, 0]`; subtract your own `vel[:2]` for relative velocity",
        "extent": "`(length, width)` in metres; a circle carries `(diameter, diameter)`",
    }
    for k in ("valid", "cls", "primitive", "pos", "heading", "vel", "extent"):
        dt, sh = _shape(ol[k])
        rows.append((f"`{k}`", dt, sh, desc[k]))
    L += _table(("key", "dtype", "shape", "meaning"), rows)
    a("")
    rows = []
    for i, cls in enumerate(CLASSES):
        prim = "circle" if cls == BUOY else "rectangle"
        sr = SIZE_RANGES[cls]
        size = (f"{sr[0]} m diameter, fixed" if cls == BUOY
                else f"{sr[0][0]:g}–{sr[0][1]:g} m × {sr[1][0]:g}–{sr[1][1]:g} m")
        moves = ("yes, on a **lane** — a fixed path between two berths or end caps, run on a schedule "
                 "(open lanes: one vessel every headway; closed lanes circulate) at %.1f–%.1f m/s, a pure "
                 "function of time (2-E2; §9); it does not react to you (2-E1)"
                 % (TRAFFIC_SPEED_MIN, TRAFFIC_SPEED_MAX) if cls == MOVING else "no")
        rows.append((i, f"`{cls}`", prim, size, moves))
    L += _table(("`cls`", "class", "primitive", "size (2-E5)", "moves"), rows)
    a("")
    n_valid = int(ol["valid"].sum())
    a(f"**The bank is not in the list** (2-E6). `meta[\"boundary\"]` already gives the "
      f"shoreline exactly, so a row for it would carry nothing — but it means an agent "
      f"driving on the object list alone drives ashore unless it puts the boundary in "
      f"itself. 1-3's ray cast hits the bank and 1-2 draws it; 1-1 does not contain it. "
      f"The example dump has {n_valid} valid rows.")
    a("")

    # 1-2
    a("### 5.2 Condition 1-2 — top-view picture (4-V6, 4-V8 revised, 4-V13 revised, 4-V17)")
    a("")
    dt, sh = _shape(img)
    a(f"A {dt} array of shape {sh}: rows × columns × RGB, {TRACK1.m_per_px} m per pixel, "
      f"{TRACK1.size_px * TRACK1.m_per_px:.0f} m across, `bow_up` — the bow points to row 0 "
      f"and the whole scene rotates with you, so consecutive frames are mutually rotated by "
      f"your yaw and `vel[2]` is what pays for compensating that (4-V2). The ego hull is "
      f"drawn. **Nothing occludes anything**: every body inside the square is drawn whole, "
      f"whatever stands in front of it (4-V17).")
    a("")
    a("**The raster is the studio's picture.** It is drawn by the same code that draws the map "
      "in `usvnav studio` and `usvnav view` (`usvnav/look.py`, 4-V13 revised 2026-09-16), so what "
      "you see there is what the agent receives — not a flat class map. The base colours, exact "
      "sRGB:")
    a("")
    appears = {UNOBSERVED: "no — it has no source in Track 1 (4-V6, 4-V17)",
               WATER: "yes", DOCK: "yes", PIER: "yes (also the rocks of a reef, 2-E12)",
               BANK: "yes — outside the boundary polygon", "vessel": "yes — moored **and** moving "
               "vessels share it; telling them apart is 1-2's task, not the palette's",
               EGO: "yes — your own hull", BUOY: "yes"}
    rows = [(f"`{name}`", _hex(rgb), str(tuple(rgb)), appears[name])
            for name, rgb in PALETTE_TRACK1.items()]
    L += _table(("class", "hex", "RGB", "appears in a 1-2 raster?"), rows)
    a("")
    a(f"`{OUTSIDE_WORLD}` is in the shared ten-class vocabulary and has **no colour** here: "
      f"generated terrain extends past the raster's {TRACK1.reach_m:.2f} m corner reach, so "
      f"it can never be painted (4-V12); if it ever had to be, the renderer raises rather "
      f"than substituting.")
    a("")
    a("**What is drawn on top of the base colours**, all of it deterministic and stated in "
      f"metres (`usvnav/look.py`): a wet band {_look.WATERLINE_M} m into the bank and a shallow "
      f"band {_look.SHALLOW_M} m into the water along every shoreline; a drop shadow "
      f"{_look.SHADOW_M} m down-right of every body; a lighter deck panel inset "
      f"{_look.DECK_INSET_M} m on piers, vessels and docks; and an outline "
      f"{_look.OUTLINE_M} m thick around every body in a darker tone (a ring outside the "
      f"footprint for buoys and your own hull). The picture is painted at "
      f"{TRACK1.m_per_px / TRACK1.subsamples} m/px and box-downsampled {TRACK1.subsamples}× to "
      f"{TRACK1.m_per_px} m/px, so edges are anti-aliased (4-V8 revised). Inside a class the colour "
      "is flat: the base colour exactly. Segment it as you would any picture — the base colours "
      "are the anchors; expect outline, shadow, shoreline and anti-aliased edge tones that are "
      "not in the table. `usvnav observe` writes the frame at any tick; the studio shows it "
      "beside the map it was drawn from.")
    a("")
    a("**Noise is yours to add.** The scorer renders with no noise at all (4-V14 revised): the "
      "picture above is what a submission is scored on. Renderer noise is an exercise you set "
      "yourself — Track 2's renders carry noise; here the tooling lets you add your own and "
      "test against it. A noise function has the shape `(class_name, x_world, y_world) -> "
      "offsets`: the class being painted, the world coordinates of every pixel centre in "
      "metres, and integer offsets added to that class's base colour. Hand it to "
      "`RasterConfig.noise`, to `usvnav run|observe|view --noise module:function`, or pick it in "
      "the studio's *noise* selector, which applies it to every run the studio starts and to "
      "*What the agent saw*; the studio's work folder gets a `noise.py` to write them in. The "
      "kit ships one example, `usvnav.look.grain` (`--noise grain`): value noise of "
      + ", ".join(f"±{a_} levels in {b_} m blocks on {n}" for n, (b_, a_) in _look.GRAIN_EXAMPLE.items() if n != OUTSIDE_WORLD)
      + ", anchored to the world so it moves with the scene.")
    a("")
    a(f"Bodies smaller than {TRACK1.min_marker_px:.1f} px are drawn at {TRACK1.min_marker_px:.1f} px "
      f"(follow-up item 5), so a {SIZE_RANGES[BUOY][0]} m buoy paints as "
      f"{TRACK1.min_marker_px * TRACK1.m_per_px:.1f} m and is never missing, while collision and "
      f"the 1-1 list keep its true size: a conservative agent gives it "
      f"{(TRACK1.min_marker_px * TRACK1.m_per_px - SIZE_RANGES[BUOY][0]) / 2:.1f} m more room "
      f"than it needs.")
    a("")
    a("A rule-based classifier is enough for this picture — the classes are a handful of "
      "known colours under small, bounded noise — and what 1-2 is testing is what comes "
      "after: objects carry no velocity and no identity, so a moving vessel is found by "
      "**associating it across frames** that your own rotation has moved, at about 0.3–0.5 px "
      "per tick.")
    a("")
    counts = {}
    flat = img.reshape(-1, 3)
    for name, rgb in PALETTE_TRACK1.items():
        counts[name] = int(np.all(flat == np.array(rgb, dtype=np.uint8), axis=1).sum())
    other = int(len(flat) - sum(counts.values()))
    a(f"In the example dump, pixels carrying a base colour exactly: "
      + ", ".join(f"`{k}` {v}" for k, v in counts.items() if v)
      + f"; the other {other} of {len(flat)} carry shoreline, shadow, deck, outline or "
      f"anti-aliased edge tones.")
    a("")

    # 1-3
    a("### 5.3 Condition 1-3 — planar LiDAR (4-V7)")
    a("")
    dt, sh = _shape(scan)
    a(f"A {dt} array of {sh} ranges in metres. Beam `i` points at bearing "
      f"`i · 2π/{N_BEAMS}` rad from the bow, **increasing to port** — {360 / N_BEAMS:.0f}° "
      f"spacing over the full 360°, so beam {N_BEAMS // 4} is abeam to port and beam "
      f"{3 * N_BEAMS // 4} to starboard. First return only, so **this is the one condition "
      f"with occlusion**: a body behind another is not reported. Single planar cast, no "
      f"mount height — the world has no vertical dimension.")
    a("")
    a(f"**No return is `{MAX_RANGE:.1f}`, the maximum range — never `0`.** A zero would be "
      f"indistinguishable from a surface at zero distance, and any agent that judges danger "
      f"by the array's minimum would read open water as an imminent collision. The bank "
      f"returns beams like any surface (2-E6).")
    a("")
    a(f"Example dump: min {scan.min():.2f} m at beam {int(scan.argmin())}, "
      f"{int((scan >= MAX_RANGE).sum())} of {N_BEAMS} beams with no return.")
    a("")

    # 1-4
    a("### 5.4 Condition 1-4 — the raster, under a disturbance (4-V10, 4-V11)")
    a("")
    a(f"`perception` is exactly 1-2's raster. What changes is the plant: an "
      f"Ornstein–Uhlenbeck drift in the **world frame** with correlation time "
      f"τ = {plant.OUDisturbance.TAU:.0f} s, bounded so the induced lateral speed never "
      f"exceeds {plant.OUDisturbance.CAP} m/s. It is smooth and mean-reverting, changes "
      f"meaningfully some sixteen times in a 333 s run, and is **not** in the observation: "
      f"you see it as the mismatch between heading and course, which is `vel[1]` — the sway "
      f"component, on top of the slip your own turns produce (which is there in every "
      f"condition). In the example dump at tick "
      f"{DUMP_TICK}, `vel` is `{_fmt(obs14['vel'])}` against `{_fmt(obs12['vel'])}` under "
      f"1-2 on the same course at the same tick.")
    a("")
    a("The generator (`usvnav.plant.OUDisturbance`) ships; hidden episodes use unseen seeds "
      "of the same family. 1-2 and 1-4 run the same courses with the same traffic and "
      "differ only in the drift (3-K6), which is what makes their score difference a "
      "diagnostic of adaptation (5-S4).")
    a("")

    # ---- outcomes
    a("## 6. How an episode ends, and the time limit (5-S11, 5-S3, 3-K11)")
    a("")
    L += _table(("outcome", "tier", "meaning"), [
        ("`goal`", "navigational", "every waypoint reached in order, the hull centre inside the "
                                   "goal radius on the last one. The only outcome that scores"),
        ("`static_collision`", "navigational", "footprint intersection with a buoy, pier, moored "
                                               "vessel or dock (2-E3), tested every tick"),
        ("`dynamic_collision`", "navigational", "footprint intersection with a moving vessel"),
        ("`out_of_bounds`", "navigational", "**any part** of the hull outside the boundary polygon "
                                            "— the shoreline; there is no separate grounding (5-S12)"),
        ("`timeout`", "navigational", f"`t` reached the limit"),
        ("`crash`", "submission fault", "`reset` or `act` raised"),
        ("`invalid_action`", "submission fault", "a non-finite or malformed action (1-W6)"),
        ("`time_overrun`", "submission fault", f"late past the per-tick wall-clock cap on more than "
                                               f"{PERSISTENT_TICKS} ticks in a row, or by more than "
                                               f"{BUDGET_CAPS} caps in all over the episode (6-R2); the "
                                               f"cap is {TICK_CAP_MS:.0f} ms (6-R3)"),
    ])
    a("")
    a(f"**Time limit: {TICK_LIMIT} ticks** ({TICK_LIMIT * plant.DT:.0f} s simulated), one "
      f"published constant for every course (5-S3, 5-S10). A run still afloat and untouched "
      f"at the limit ends as `timeout` and earns partial credit for the waypoints it reached "
      f"(§5 of RULES.md); dawdling is otherwise priced by the time item. It will not go below "
      f"the ~3330 ticks a straight run of the longest course needs.")
    a("")
    a("Within one tick the checks run in a fixed order so a re-run reproduces the outcome: "
      "submission fault → collision → out-of-bounds → goal → timeout.")
    a("")
    a(f"**Clearance**, the item scoring rewards (5-S13): per tick, the minimum "
      f"surface-to-surface distance from the hull rectangle to any body **or the bank**, "
      f"capped at {D_CAP:.0f} m; the episode statistic is the mean of the lowest "
      f"{CLEARANCE_PERCENTILE:.0f}% of those per-tick minima. Open water you happened to "
      f"cross cannot raise it.")
    a("")

    # ---- courses
    a("## 7. What the courses contain (2-E4, 2-E5, 2-E1, 3-K3, 3-K10, 7-A8)")
    a("")
    a(f"A course is a stretch of river with a shoreline, a start pose, a chain of {WP_MIN}–{WP_MAX} "
      f"waypoints on legs of {LEG_MIN:g}–{LEG_MAX:g} m (3-K5) — across the width, and out and back "
      f"with the goal beside the start — static bodies of the classes in §5.1 with the "
      "sizes given there, and moving vessels on lanes (§9). The world is a 400 × 150 m "
      "box (1-W2); the channel is 40–120 m wide. Nothing else about how the hidden courses are "
      "composed is disclosed — **what they test is published as a list of capabilities in "
      "`docs/RULES.md` §1**, and the one numeric constraint is that no passage on a hidden "
      "route is narrower than %g m, two hull widths (3-K10)." % (2.0 * plant.HULL_WIDTH))
    a("")
    a("The practice courses in `sets/practice/` are a few composite courses of low-to-medium "
      "difficulty (3-K3). They show the format and the feel of a course, not the range of what "
      "the hidden set contains; the courses you test against are the ones you author in the "
      "editor or write as files (§9). Every hidden course passes the same course-file rules the studio and `usvnav validate` "
      "apply. No competent agent is distributed (7-A1); the shipped tutorial agent usually fails.")
    a("")

    # ---- dumps
    a("## 8. The example dumps (`docs/examples/`)")
    a("")
    a(f"One course (`course.json`), its `meta.json`, and the observation at tick {DUMP_TICK} "
      f"under each condition, driven there by the shipped tutorial agent and captured from "
      f"`sim.run_episode` itself:")
    a("")
    a("- `observation-1-1.json` — the six common fields and the full object list, padding included;")
    a("- `observation-1-2.png` — the raster, pixel-exact (open it with any image library; "
      "the `-x3` copy is upscaled by nearest neighbour for looking at); "
      "`observation-1-2.json` — the common fields and the per-class pixel counts;")
    a("- `observation-1-3.json` — the common fields and the 180 ranges;")
    a("- `observation-1-4.json` / `.png` — the same, under the disturbance: compare `vel` "
      "and `pose` with 1-2's.")
    a("")
    a("Regenerate everything with `usvnav docs`; `usvnav observe COURSE --condition C` "
      "writes a single tick of your own.")
    a("")
    _course_file_section(a)
    return "\n".join(L)


def _course_file_section(a):
    """§9 of OBSERVATION.md: the course file, so a team can write any course by hand — lanes
    included. Format and rules only; nothing about how the hidden courses are composed."""
    (l_lo, l_hi), (w_lo, w_hi) = SIZE_RANGES[MOVING]
    a(f"## 9. The course file (`{coursefile.FORMAT}`)")
    a("")
    a("Everything the studio, `usvnav validate`, `usvnav run` and the scorer read is one JSON file; "
      "the practice courses and `docs/examples/course.json` are examples. Metres and radians (1-W3), "
      "`+x` along the reach, `+y` to port; coordinates are written to four decimals, and the file — not "
      "the object that produced it — is what runs. The editor writes it, and you can write it yourself:")
    a("")
    a("```")
    a("{\"format\": \"%s\"," % coursefile.FORMAT)
    a(" \"world\": {\"boundary\": [[x, y], ...]},                 the navigable polygon; water at the box's x-edges is an end cap")
    a(" \"start\": {\"x\": .., \"y\": .., \"heading_rad\": ..},")
    a(" \"waypoints\": [{\"x\": .., \"y\": .., \"arrival_radius_m\": 5.0}, ..., {\"..\": .., \"arrival_radius_m\": 3.0}],")
    a(" \"bodies\": [{\"class\": \"buoy\", \"primitive\": \"circle\", \"x\": .., \"y\": .., \"diameter_m\": 0.6},")
    a("            {\"class\": \"pier\" | \"moored_vessel\" | \"dock\", \"primitive\": \"rect\", \"x\": .., \"y\": .., \"length_m\": .., \"width_m\": .., \"heading_rad\": ..}],")
    a(" \"traffic\": [],                                            legacy closed loops (class, length_m, width_m, speed_mps, phase_m, route); lanes replace them")
    a(" \"lanes\": [{\"class\": \"moving_vessel\", \"closed\": false,")
    a("            \"route\": [[x0, y0], [x1, y1], ...],              the path, 2 or more points (a closed lane 3 or more)")
    a("            \"speeds_mps\": [v0, v1, ...],                      one speed per route point, linear in between")
    a("            \"headway_s\": 45.0, \"offset_s\": 0.0,             open lanes: a vessel enters at route[0] every headway_s seconds, shifted by offset_s")
    a("            \"vessels\": [{\"length_m\": 12, \"width_m\": 3}, ...]}]}  the sizes the vessels cycle through")
    a("```")
    a("")
    a(f"**Lanes** are how vessels move. An *open* lane's vessels appear at its first point on the schedule, run "
      f"the route at the speeds given, and leave at its last point; both ends should sit on a *spawn wall* — "
      f"an end cap (the water's edge at the world box) or a **berth**, a slip cut into the shoreline polygon "
      f"— so a vessel is never seen appearing on open water. A *closed* lane's vessels circulate, spaced "
      f"equally in time (no `headway_s`). Every pose is a pure function of time, so a run is reproducible "
      f"and a vessel never reacts to you. `waypoints`: {WP_MIN}–{WP_MAX}, legs {LEG_MIN:g}–{LEG_MAX:g} m, "
      f"intermediate radius {RADIUS_INTERMEDIATE:g} m and the goal {RADIUS_GOAL:g} m (3-K5, 3-K11).")
    a("")
    a("**What `usvnav validate FILE` (and the studio, on every save) checks about lanes** — each problem "
      "names its rule and says what to change:")
    a("")
    a(f"- L1 the corridor (the widest vessel plus {LANE_CLEAR:g} m each side) is clear of bodies and of the shore;")
    a(f"- L2 speeds within {TRAFFIC_SPEED_MIN:g}–{TRAFFIC_SPEED_MAX:g} m/s (2-E2), acceleration between points at most {A_MAX:g} m/s²;")
    a(f"- L3/L4 the spacing guarantee: at the speed where your route meets the lane, `headway · v − L ≥ {EGO_SLOT:g} m` "
      f"(room for the hull between two vessels), and at every passage too narrow to pass beside a vessel the headway "
      f"leaves time to get through at {V_WAIT:g} m/s — so a lane can always be crossed by waiting for the gap;")
    a("- L5 lanes do not touch each other; L7 the corridor keeps out of the start pose and the goal's disc; "
      f"L8 no lane vessel within {SENSING_RANGE:g} m of the start at t = 0;")
    a(f"- L9 vessels {l_lo:g}–{l_hi:g} m × {w_lo:g}–{w_hi:g} m (2-E5) and a metre narrower than the lane's tightest passage; "
      f"L11 no turn over {LANE_TURN_MAX_DEG:g}° at a route point (insert points to round a corner); "
      "L10 (a warning) an open lane that does not end on a spawn wall.")
    a("")
    a("Static bodies follow 2-E5's sizes (§5.1), keep off the start pose and every arrival disc (2-E11, 3-K14), "
      "and must leave the route connected through free water for the hull (3-K9). The editor's own checks are the "
      "subset that needs no free-space grid; the studio's save and `usvnav validate` run the whole list.")


# --------------------------------------------------------------------------- RULES.md

def rules_md() -> str:
    L = []
    a = L.append
    a("# Track 1 — rules of submission and execution")
    a("")
    a(STAMP)
    a("")
    a("**What the track asks for.** A good rule-based autonomy policy for a 3 × 2 m boat on "
      "a river reach, run under four observation conditions by one agent (0-P3). Learned "
      "components are permitted and unrestricted (6-R4) — nothing about them has to be "
      "declared — but the track is not asking for them, and the shipped tooling assumes "
      "nothing about a model being present. The problem is defined by §1's capability list, "
      "the schema in `docs/OBSERVATION.md`, and the scoring in §5; the evaluation courses "
      "themselves are hidden, and you build your own test cases in the studio (7-A8): "
      "`usvnav studio` opens the course editor, runs the agent you choose on the course you "
      "drew under the condition and seed you pick, and plays the run back (7-A2).")
    a("")
    a("## 1. What the hidden set evaluates (7-A9)")
    a("")
    a("The hidden courses are built to exercise the capabilities below, and every one of them "
      "is scored through the same four numbers — completion, control effort, clearance, time (§5). "
      "Nothing else about the hidden courses is disclosed: not how many there are of what, "
      "not how they are composed. This list is the problem definition; the courses you test "
      "against are the ones you author. A solution should be able to:")
    a("")
    caps = (
        f"**Follow a route.** Reach {WP_MIN}–{WP_MAX} waypoints in order along a river reach, on legs of "
        f"{LEG_MIN:g}–{LEG_MAX:g} m — across the width, and out and back with the goal beside the start — "
        f"arriving within {RADIUS_INTERMEDIATE:g} m of each intermediate waypoint and within {RADIUS_GOAL:g} m of the "
        "goal, measured to the hull centre — without any part of the hull crossing the shoreline.",
        "**Keep clear of static bodies** of five classes with their true footprints, from a "
        "0.6 m buoy to a 40 m moored vessel, and choose how much clearance to trade for "
        "directness: both are scored, against the best submission on the same course.",
        f"**Pass narrow gaps.** No passage on a hidden route is narrower than "
        f"{2.0 * plant.HULL_WIDTH:g} m, two hull widths, and passages down to that width occur.",
        "**Choose between routes** when the direct way is tight and an indirect way is open, "
        "including when the far side of a gap is not visible from its entrance.",
        f"**Predict and avoid moving vessels** that run on lanes between berths and end caps, on a "
        f"schedule, at {TRAFFIC_SPEED_MIN:g}–{TRAFFIC_SPEED_MAX:g} m/s, and never give way to you — "
        f"crossing a lane means waiting for the gap between two vessels; under 1-2 "
        f"and 1-3 the observation carries no velocity and no identity, so their motion has to be "
        f"recovered from consecutive observations.",
        "**Slow down, stop and wait** when the water ahead is not clear, and get going again.",
        f"**Reverse** (down to {plant.V_MIN:g} m/s) out of a bad commitment — a dead end, an "
        f"over-run approach.",
        "**Turn where the straight line between consecutive waypoints crosses the bank:** the "
        "chain is a route through the channel, not a set of straight legs.",
        "**Dock:** finish within 3 m of a goal that sits beside a dock structure without touching it.",
        f"**Compensate a drift** under 1-4: a slowly varying lateral drift of up to "
        f"{plant.OUDisturbance.CAP} m/s, observable only as the mismatch between heading and "
        f"course (`vel[1]`) beyond the hull's own slip in turns, to be estimated and corrected online.",
        "**Do all of it from each of the four observation types with one agent,** within the "
        "time limit, deterministically — the same episode driven twice must give the same run.",
    )
    for k, c in enumerate(caps, 1):
        a(f"{k}. {c}")
    a("")
    a("## 2. The interface (6-R6, 6-R8)")
    a("")
    a("`Agent(config_path)` at construction, `reset(meta)` at episode start, "
      "`act(obs) -> [v_cmd, w_cmd]` every tick. `config_path` is the absolute path of a "
      "file inside your submission. No state may carry across episodes: a re-run of any "
      "single episode must reproduce its trace, which is what dispute resolution rests on "
      "(3-K6). The schema is `docs/OBSERVATION.md`.")
    a("")
    a("## 3. The submission (6-R9, 6-R10)")
    a("")
    a(f"A **directory** — see `docs/PACKAGING.md`: the agent module, its config, weights if "
      f"any, a `{MANIFEST}` manifest and a `{DOC}`. Under {SIZE_CAP_BYTES // 2**20} MB (6-R9a). "
      f"`usvnav validate-submission DIR` applies every rule mechanically before you submit; "
      f"a submission it rejects is not run. A container image is being considered for the "
      f"public release and is **not** the form now.")
    a("")
    a("**Submitting** (owner, 2026-09-14; the common rules, §2). You submit with the `submit.py` "
      "at the top of the kit — the organisers' script, the same for every track — over the SFTP "
      "account your team is issued:")
    a("")
    a("```")
    a("python submit.py track1 ./my_sub --team <team id> --host <scoring host>")
    a("python submit.py status --team <team id> --host <scoring host>      # your receipts")
    a("```")
    a("")
    a("The script refuses locally what the intake would refuse, uploads the directory into your "
      "team's `track1` slot, and then places a marker `<name>.submit` beside it (JSON: `format` "
      "`hangang-submit/1`, `team`, `slot`, `name`, the `sha256` of the upload, `submitted_at`). "
      "**An upload is a submission only when its marker is there and matches the upload**, and "
      "then it is taken at once. An upload without a marker is not looked at and gets no receipt; "
      "a marker that does not match, once the upload has stopped changing, is `refused` — run "
      "`submit.py` again when the upload is complete. A name is never overwritten (pick a new "
      "`--name`), and the same bytes as an earlier submission are `duplicate`. **Deadline:** a "
      "submission is in when its marker has arrived and matches; an upload without a marker, or "
      "whose marker does not match, at the deadline is not a submission.")
    a("")
    a("**Intake** (operations, decided 2026-09-13): the manifest's `team` must be your team id — "
      "the name of your team's folder at the intake — or the submission is refused; **at most 5 "
      "scored submissions per team in any rolling 24 hours** — one over the quota is held and "
      "scored when the window clears; every submission gets a receipt, `queued` / `scored` / "
      "`refused` / `duplicate`, as `track1/.hangang/<name>.json` in your slot. Your **best** "
      "accepted submission counts (6-R11).")
    a("")
    a("## 4. How a submission is executed (6-R1, 6-R5, 6-R7, 6-R7b)")
    a("")
    a("- **No network.** Anything the agent loads is inside the directory.")
    a("- **A GPU is available, and a submission must fit in 8 GB of it** — the budget is a "
      "4060-class card (6-R1). The scoring machine's card is a 16 GB 4080-class shared between "
      "two submissions at a time, which is what the 8 GB budget makes safe. Participants are "
      "not issued a GPU.")
    a("- **The agent runs in a child process of the runner.** Only the observation and the "
      "action cross the boundary. Simulator internals — the hidden course, traffic futures, "
      "the disturbance — are unreachable rather than forbidden, so no rule is written about "
      "them. One rule is: **reading the filesystem outside the submitted directory is "
      "prohibited**, and a detected attempt is **disqualification**, not a scored zero. On the "
      "scoring machine the agent's process also runs in a private filesystem that holds only the "
      "interpreter, `usvnav`, your submission (read-only) and a scratch directory, with no network.")
    a(f"- **Scoring is not real time.** The runner blocks on `act()`; 10 Hz is simulated time. "
      f"A per-tick wall-clock cap exists as a throughput guard and **never affects the "
      f"score**. It is measured at the process boundary from sending the observation to "
      f"receiving the action, and is **{TICK_CAP_MS:.0f} ms** — {TICK_CAP_MULTIPLE}× "
      f"the {TICK_FLOOR_MS} ms a good-faith agent measured under the image conditions (6-R3; "
      f"not the 100 ms control period, which is simulated). A reply later than "
      f"the cap is discarded and the previous action is applied again for that tick; more than "
      f"{PERSISTENT_TICKS} late ticks in a row, or lateness adding up to more than {BUDGET_CAPS} "
      f"caps over an episode, fails it as `time_overrun` (6-R2). A reasonably sized submission "
      f"has large headroom and no reason to sit near the cap.")
    a("- **One process pair per (team, condition)**, running that condition's episodes "
      "sequentially with `reset()` between them; what you load at construction is loaded "
      "four times per submission, not once per episode.")
    a("- **Pretrained weights and external data are unrestricted** and need no declaration "
      "(6-R4). Prohibitions in other tracks do not reach here.")
    a("")
    a("## 5. Scoring (5-S1, 5-S6, 5-S8, 5-S9, 5-S11, 5-S13)")
    a("")
    w = WEIGHTS
    a(f"Per **episode**, three items — control effort (fuel), clearance, time — each divided by the "
      f"best value among the submissions that **completed that episode** (fuel and time as "
      f"best/yours, clearance as yours/best), so each lands in (0, 1]. **Control effort (fuel)** is the "
      f"sum over the episode's ticks of `(Δv_cmd / V_MAX)² + (Δω_cmd / W_MAX)²` of the applied action, "
      f"starting from rest: a run with fewer and gentler speed and heading changes burns less. "
      f"A run that does not complete never enters the episode's best. **A timeout** — the "
      f"time limit reached without touching anything — scores **(k/N)² times the lowest "
      f"score among the episode's completers**, k the waypoints it reached in order and N the "
      f"course's waypoints; its own fuel, clearance and time are not used. A collision, "
      f"out-of-bounds or submission fault scores 0, and if nobody completes an episode, "
      f"everybody scores 0 on it, a timeout included. The episode scores are averaged over "
      f"the condition's episodes, "
      f"weighted **fuel {w['fuel']:.1f} / clearance {w['clearance']:.1f} / time "
      f"{w['time']:.1f}**, and the final score is the **weighted mean of the four condition "
      f"scores** — " + ", ".join(f"{c} at {100 * v:.0f}%" for c, v in CONDITION_WEIGHTS.items())
      + " (5-S8) — published alongside them. There is no reference path and no reference "
      f"time (5-S2).")
    a("")
    a(f"Clearance counts every surface, the bank included: the mean of the lowest "
      f"{CLEARANCE_PERCENTILE:.0f}% of per-tick minimum distances, each capped at "
      f"{D_CAP:.0f} m first (5-S13, 5-S13a). The percentile is what bounds the clearance term: "
      f"it samples the tightest seconds of the run, so a wide detour in open water does not pay "
      f"(5-S7a); the cap is a guard against a pathological course and moves no score.")
    a("")
    a("**Ties** are broken by full-precision score, then total waypoints reached across all "
      "episodes, then the earlier submission timestamp (5-S9); ties happen only among "
      "submissions that completed nothing.")
    a("")
    a(f"**Time limit:** {TICK_LIMIT} ticks per episode (5-S3, 5-S10). "
      f"Outcomes: {', '.join(f'`{o}`' for o in NAVIGATIONAL)} are navigational; "
      f"{', '.join(f'`{o}`' for o in SUBMISSION_FAULT)} are submission faults. Only `goal` "
      f"and `timeout` score (above).")
    a("")
    a("## 6. What you see during the contest (3-K8, 5-S4, 5-S5)")
    a("")
    a("The leaderboard computes exactly the final procedure against the field submitted so "
      "far, on the one hidden set; there are no organiser reference figures. It shows every "
      "team's final and per-condition scores. Your own page shows your **per-episode "
      "scores** by episode id, your **failure-cause distribution** (navigational tier only — "
      "submission faults are listed separately, because a bug is not a weakness), and the "
      "1-2 versus 1-4 difference. Per-type completion rates are not published. **Your best "
      "accepted submission is the one that counts** (6-R11); every submission you made is "
      "listed on your page with the counting one marked.")
    a("")
    a("## 7. The courses (3-K3, 7-A1, 7-A8)")
    a("")
    a("`sets/practice/` holds a few composite courses of low-to-medium difficulty: enough to "
      "see the format and run the tooling, not a sample of the hidden set. You are expected "
      "to imagine the hard cases yourself and build them in the editor. **Every hidden course "
      "passes the same course-file rules** the studio and `usvnav validate` apply. **No competent "
      "agent is distributed** (7-A1), and the shipped tutorial agent usually "
      "fails a course — so a team wanting to confirm its setup should author an easy course "
      "in the studio. The generator that draws the hidden courses is an organiser tool and is "
      "not in the kit (7-A8). Hidden episodes are rendered by the code shipped to you "
      "(T1-SCO-06), which is frozen for the contest's duration (follow-up item 15).")
    a("")
    a("## 8. Provisional values")
    a("")
    a("Stated so that nothing here is quoted as final that is not. Each will be fixed before "
      "the contest opens and announced with the reason:")
    a("")
    L += _table(("value", "current", "waits on"), [
        ("hidden-set episode counts (3-K7)", "not fixed", "the field size (0-P2)"),
        ("submissions per team", "5 scored in any rolling 24 h, at the intake", "operations (decided 2026-09-13)"),
    ])
    return "\n".join(L)


# --------------------------------------------------------------------------- RUNTIME.md

def runtime_md() -> str:
    R = runtime.RUNTIME
    L = ["# Track 1 — the scoring runtime", "", STAMP, "",
         f"What a submission meets at scoring time, identified as `{R['id']}` — the value "
         f"the manifest's `runtime` field must carry.", ""]
    cuda = ", ".join(f"`{k}=={v}`" for k, v in R["cuda"].items())
    L += _table(("what", "value"), [
        ("Python", f"{R['python']} (major.minor pinned; the patch level is not)"),
        *[(f"`{k}`", f"{v}, pinned exactly") for k, v in R["packages"].items()],
        ("CUDA libraries", f"the pip packages onnxruntime-gpu loads, pinned exactly: {cuda}"),
        ("execution providers", ", ".join(f"`{p}`" for p in R["providers"])),
        ("other packages", "**none** — anything else your agent imports must be inside your "
                           "submission directory, as pure Python or as wheels you unpack there"),
        ("network", "none (6-R1)"),
        ("GPU", R["gpu"]),
        ("submission form", R["submission_form"]),
        ("agent process", R["agent_process"]),
        ("wall clock", R["wall_clock"]),
    ])
    ort = R["packages"]["onnxruntime-gpu"]
    np_ver = R["packages"]["numpy"]
    pins = " ".join(f"{k}=={v}" for k, v in R["cuda"].items())
    L += ["",
          "The interpreter and the package set are frozen for the contest's duration "
          "(follow-up item 15). The shipped `usvnav` package depends on numpy and nothing "
          "else for the same reason: everything the scorer runs has to exist on a machine "
          "with no network.",
          "",
          "## onnxruntime (6-R12)",
          "",
          "The runtime provides `onnxruntime`, GPU build, so a learned component (6-R4) has "
          "one framework-neutral way to run: export to ONNX from PyTorch, TensorFlow or JAX, "
          "ship the `.onnx` file inside your submission, and open it with "
          "`onnxruntime.InferenceSession(path, providers=[\"CUDAExecutionProvider\", "
          "\"CPUExecutionProvider\"])`. It is the same version Track 3 pins, installed once on the "
          "scoring machine; nothing else about it is configured (default session options, no "
          "TensorRT). The CUDA provider is a pure win only for a model large enough to amortise "
          "the copy; a small network is often faster on the CPU provider, and the per-tick wall "
          "clock is yours either way (6-R3).",
          "",
          "To match it locally — the interpreter and numpy too, not only onnxruntime: the kit "
          f"installs on any Python from 3.10 and any numpy from 1.24, but the scorer runs Python "
          f"{R['python']} and numpy {np_ver}, and numpy 1.x and 2.x differ in type promotion and "
          "copy semantics, so develop on the scorer's versions:",
          "",
          "```",
          f"python --version                        # {R['python']}.x, the scorer's interpreter",
          f"pip install numpy=={np_ver}",
          f"pip install onnxruntime-gpu=={ort} {pins}",
          f"pip install onnxruntime=={ort}          # CPU build: same API, same numbers to float precision, "
          "no card needed",
          "```",
          "",
          "The GPU build finds its CUDA libraries in those pip packages; no system CUDA install "
          "is needed or used. The scoring machine has been checked against this table: every "
          "version above is what is installed there, and a model has been run on its "
          "`CUDAExecutionProvider` (`tests/internal/test_runtime.py`, organisers' side)."]
    return "\n".join(L)


# --------------------------------------------------------------------------- PACKAGING.md

def packaging_md() -> str:
    L = ["# Track 1 — submission packaging", "", STAMP, "",
         "A submission is a **directory** (6-R10). What is in it is 6-R9's list, as files:", "",
         "```",
         "my-submission/",
         f"  {MANIFEST}     the manifest (below)",
         "  agent.py            exposes `Agent(config_path)` -- the interface of 6-R6",
         "  config.json         anything you like; its absolute path is what `Agent()` receives",
         f"  {DOC}       required; read by nobody who scores",
         "  weights/ ...        optional; no network at scoring time, so anything you load is here",
         "```", "",
         f"## The manifest, `{MANIFEST}`", "",
         "```json", json.dumps({"format": FORMAT, "team": "herons", "entry": "agent:Agent",
                                "config": "config.json", "runtime": runtime.RUNTIME_ID}, indent=1),
         "```", ""]
    L += _table(("key", "meaning"), [
        ("`format`", f"`{FORMAT}`"),
        ("`team`", f"your team's name as it appears on the leaderboard and names your page; "
                   f"`{TEAM_RE.pattern}`"),
        ("`entry`", "`module:Class`; the module is a `.py` file or a package inside the directory"),
        ("`config`", "a path inside the directory; passed to `Agent()` as an absolute path"),
        ("`runtime`", f"the runtime you expect: `{runtime.RUNTIME_ID}` (`docs/RUNTIME.md`)"),
    ])
    L += ["", f"All {len(REQUIRED)} keys are required. `{DOC}` is required as well and is "
          f"neither scored nor verified: its honest uses are letting the organisers debug a "
          f"failing submission and letting results be interpreted afterwards.", "",
          "## The local validator", "",
          "```", "usvnav validate-submission my-submission/", "```", "",
          "Every requirement is mechanically checkable, and the validator checks every one, "
          "each line naming the decision it enforces. The static checks run first; if they "
          "pass, a **smoke run** constructs your agent in a child process, calls `reset` with "
          "a real course's metadata and drives it for a few hundred ticks under each condition "
          "through the same `run_episode` the scorer uses — so an interface mistake cannot pass "
          "here and fail there. The tutorial agent passes; the validator says nothing about "
          "whether an agent is any good.", ""]
    L += _table(("check", "what passes", "decision"), [(f"`{c}`", what, why) for c, what, why in CHECKS])
    L += ["", "A submission the validator rejects is not run and not stored by the leaderboard. "
          "`--out report.json` writes the full report; `--conditions 1-1,1-3 --ticks 60` makes "
          "a quick pass while iterating.", "",
          "## The worked example", "",
          "`examples/submission/` is a complete, valid submission: a pure-pursuit follower that "
          "reads the perception field of each condition and slows when something is close "
          "ahead. Copy it, rename the team, and replace `agent.py`. It is tutorial-grade on "
          "purpose (7-A1) — it completes open reaches and little else."]
    return "\n".join(L)


# --------------------------------------------------------------------------- build

def build(out: pathlib.Path | None = None) -> dict:
    """Return `{relative path: bytes}` of every generated file."""
    course = _course()
    captures = {c: capture(course, c) for c in CONDITIONS}
    files: dict[str, bytes] = {}

    files["OBSERVATION.md"] = (observation_md(course, captures) + "\n").encode()
    files["RULES.md"] = (rules_md() + "\n").encode()
    files["RUNTIME.md"] = (runtime_md() + "\n").encode()
    files["PACKAGING.md"] = (packaging_md() + "\n").encode()

    import io
    import tempfile
    with tempfile.TemporaryDirectory() as tmp:
        p = pathlib.Path(tmp) / "course.json"
        coursefile.save(course, p)
        files["examples/course.json"] = p.read_bytes()
        meta = captures["1-1"][0]
        files["examples/meta.json"] = (json.dumps(_listify(dict(meta)), indent=1) + "\n").encode()
        for cond in CONDITIONS:
            _, obs = captures[cond]
            common = {k: _listify(v) for k, v in obs.items() if k != "perception"}
            per = obs["perception"]
            if cond == "1-1":
                common["perception"] = _listify(per)
            elif cond == "1-3":
                common["perception"] = _listify(per)
            else:
                png = pathlib.Path(tmp) / f"{cond}.png"
                write_png(png, per)
                files[f"examples/observation-{cond}.png"] = png.read_bytes()
                if cond == "1-2":
                    write_png(png, per, scale=3)
                    files["examples/observation-1-2-x3.png"] = png.read_bytes()
                flat = per.reshape(-1, 3)
                counts = {name: int(np.all(flat == np.array(rgb, dtype=np.uint8), axis=1).sum())
                          for name, rgb in PALETTE_TRACK1.items()}
                common["perception"] = {"file": f"observation-{cond}.png",
                                        "shape": list(per.shape), "dtype": str(per.dtype),
                                        "exact_colour_pixels": counts,
                                        "boundary_pixels": int(len(flat) - sum(counts.values()))}
            files[f"examples/observation-{cond}.json"] = (json.dumps(common, indent=1) + "\n").encode()
    if out is not None:
        for rel, data in files.items():
            path = pathlib.Path(out) / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    return files


def check(out: pathlib.Path = DOCS) -> list[str]:
    """Which generated files differ from (or are missing in) `out`."""
    files = build(None)
    bad = []
    for rel, data in files.items():
        path = pathlib.Path(out) / rel
        if not path.is_file() or path.read_bytes() != data:
            bad.append(rel)
    return bad


def cmd_docs(args) -> int:
    out = pathlib.Path(args.out) if args.out else DOCS
    if args.check:
        bad = check(out)
        for rel in bad:
            print(f"  [stale ] {rel}")
        print("docs match the code" if not bad else f"{len(bad)} file(s) differ; run `usvnav docs`")
        return 1 if bad else 0
    files = build(out)
    for rel in files:
        print(f"  wrote {out / rel}")
    return 0
